# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
os:
  # edit: "nvim {{filename}}"

  # editAtLine: "nvim {{filename}} +{{line}}"

  open: zsh -c 'nvim {{filename}}'
gui:
  switchTabsWithPanelJumpKeys: true
  commit:
    template: ~/.angular_commit_template.txt

